server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 8989
  context-path: /ems_fenhong

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .jsp
      prefix: /ems1.0/
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*.xml
